export const NEW_RECIPES = [
    {
        id: '1',
        title: 'Солянка с грибами',
        description:
            'Как раз после праздников, когда мясные продукты еще остались, но никто их уже не хочет, время варить солянку.',
        image: '/img/new-recipes/1.jpg',
        category: ['first-dish', 'national'],
        subcategory: ['soups', 'vegetables'],
        bookmarks: 1,
        likes: 0,
        date: '2025-03-10T00:00:00Z',
        portions: 4,
        nutritionValue: { calories: 150, proteins: 5, fats: 3, carbohydrates: 25 },
        ingredients: [
            { title: 'грибы', count: '200', measureUnit: 'г' },
            { title: 'картошка', count: '3', measureUnit: 'шт.' },
            { title: 'морковь', count: '1', measureUnit: 'шт.' },
            { title: 'лук', count: '1', measureUnit: 'шт.' },
        ],
        steps: [
            {
                stepNumber: 1,
                description: 'Нарезать грибы и картошку.',
                image: '/img/cook-steps/1.jpg',
            },
            {
                stepNumber: 2,
                description: 'Обжарить картошку и морковь.',
                image: '/img/cook-steps/2.jpg',
            },
            {
                stepNumber: 3,
                description: 'Добавить грибы и тушить.',
                image: '/img/cook-steps/3.jpg',
            },
        ],
    },
    {
        id: '2',
        title: 'Капустные котлеты',
        description:
            'Капустные котлеты по этому рецепту получаются необычайно пышными и невероятно вкусными.',
        image: '/img/new-recipes/2.jpg',
        category: ['vegan', 'snacks'],
        subcategory: ['vegetables', 'warm-snacks'],
        bookmarks: 2,
        likes: 1,
        date: '2024-03-05T00:00:00Z',
        portions: 4,
        nutritionValue: { calories: 120, proteins: 3, fats: 2, carbohydrates: 15 },
        ingredients: [
            { title: 'капуста', count: '500', measureUnit: 'г' },
            { title: 'мука', count: '100', measureUnit: 'г' },
            { title: 'чеснок', count: '2', measureUnit: 'зубчика' },
        ],
        steps: [
            { stepNumber: 1, description: 'Измельчить капусту.', image: '/img/cook-steps/1.jpg' },
            {
                stepNumber: 2,
                description: 'Смешать с мукой и чесноком.',
                image: '/img/cook-steps/2.jpg',
            },
            {
                stepNumber: 3,
                description: 'Сформировать котлеты и обжарить.',
                image: '/img/cook-steps/3.jpg',
            },
        ],
    },
    {
        id: '3',
        title: 'Оладьи на кефире "Пышные"',
        description:
            'Очень вкусные и нежные оладьи на кефире. Настоятельно рекомендую для завтрака.',
        image: '/img/new-recipes/3.jpg',
        category: ['deserts', 'national'],
        subcategory: ['baking', 'sweet-desserts'],
        bookmarks: 0,
        likes: 1,
        date: '2024-02-25T00:00:00Z',
        portions: 6,
        nutritionValue: { calories: 250, proteins: 5, fats: 10, carbohydrates: 30 },
        ingredients: [
            { title: 'кефир', count: '200', measureUnit: 'мл' },
            { title: 'мука', count: '150', measureUnit: 'г' },
            { title: 'сахар', count: '50', measureUnit: 'г' },
        ],
        steps: [
            {
                stepNumber: 1,
                description: 'Смешать кефир, муку и сахар.',
                image: '/img/cook-steps/1.jpg',
            },
            { stepNumber: 2, description: 'Сформировать тесто.', image: '/img/cook-steps/2.jpg' },
            { stepNumber: 3, description: 'Жарить на сковороде.', image: '/img/cook-steps/3.jpg' },
        ],
    },
    {
        id: '4',
        title: 'Салат "Здоровье"',
        description: 'Сельдерей очень полезен для здоровья, пора набираться витаминов.',
        image: '/img/new-recipes/4.jpg',
        category: ['salads'],
        subcategory: ['vegetables', 'cold-salads'],
        bookmarks: 0,
        likes: 0,
        date: '2025-03-01T00:00:00Z',
        portions: 2,
        nutritionValue: { calories: 50, proteins: 1, fats: 0, carbohydrates: 5 },
        ingredients: [
            { title: 'сельдерей', count: '200', measureUnit: 'г' },
            { title: 'яблоко', count: '1', measureUnit: 'шт.' },
            { title: 'сметана', count: '50', measureUnit: 'г' },
        ],
        steps: [
            {
                stepNumber: 1,
                description: 'Нарезать сельдерей и яблоко.',
                image: '/img/cook-steps/1.jpg',
            },
            { stepNumber: 2, description: 'Заправить сметаной.', image: '/img/cook-steps/2.jpg' },
        ],
    },
    {
        id: '5',
        title: 'Солянка с грибами',
        description:
            'Как раз после праздников, когда мясные продукты еще остались, но никто их уже не хочет, время варить солянку.',
        image: '/img/new-recipes/1.jpg',
        category: ['first-dish', 'national'],
        subcategory: ['soups', 'vegetables'],
        bookmarks: 1,
        likes: 0,
        date: '2025-03-10T00:00:00Z',
        portions: 4,
        nutritionValue: { calories: 150, proteins: 5, fats: 3, carbohydrates: 25 },
        ingredients: [
            { title: 'грибы', count: '200', measureUnit: 'г' },
            { title: 'картошка', count: '3', measureUnit: 'шт.' },
            { title: 'морковь', count: '1', measureUnit: 'шт.' },
            { title: 'лук', count: '1', measureUnit: 'шт.' },
        ],
        steps: [
            {
                stepNumber: 1,
                description: 'Нарезать грибы и картошку.',
                image: '/img/cook-steps/1.jpg',
            },
            {
                stepNumber: 2,
                description: 'Обжарить картошку и морковь.',
                image: '/img/cook-steps/2.jpg',
            },
            {
                stepNumber: 3,
                description: 'Добавить грибы и тушить.',
                image: '/img/cook-steps/3.jpg',
            },
        ],
    },
    {
        id: '6',
        title: 'Капустные котлеты',
        description:
            'Капустные котлеты по этому рецепту получаются необычайно пышными и невероятно вкусными.',
        image: '/img/new-recipes/2.jpg',
        category: ['vegan', 'snacks'],
        subcategory: ['vegetables', 'warm-snacks'],
        bookmarks: 2,
        likes: 1,
        date: '2024-03-05T00:00:00Z',
        portions: 4,
        nutritionValue: { calories: 120, proteins: 3, fats: 2, carbohydrates: 15 },
        ingredients: [
            { title: 'капуста', count: '500', measureUnit: 'г' },
            { title: 'мука', count: '100', measureUnit: 'г' },
            { title: 'чеснок', count: '2', measureUnit: 'зубчика' },
        ],
        steps: [
            { stepNumber: 1, description: 'Измельчить капусту.', image: '/img/cook-steps/1.jpg' },
            {
                stepNumber: 2,
                description: 'Смешать с мукой и чесноком.',
                image: '/img/cook-steps/2.jpg',
            },
            {
                stepNumber: 3,
                description: 'Сформировать котлеты и обжарить.',
                image: '/img/cook-steps/3.jpg',
            },
        ],
    },
    {
        id: '7',
        title: 'Оладьи на кефире "Пышные"',
        description:
            'Очень вкусные и нежные оладьи на кефире. Настоятельно рекомендую для завтрака.',
        image: '/img/new-recipes/3.jpg',
        category: ['deserts', 'national'],
        subcategory: ['baking', 'sweet-desserts'],
        bookmarks: 0,
        likes: 1,
        date: '2024-02-25T00:00:00Z',
        portions: 6,
        nutritionValue: { calories: 250, proteins: 5, fats: 10, carbohydrates: 30 },
        ingredients: [
            { title: 'кефир', count: '200', measureUnit: 'мл' },
            { title: 'мука', count: '150', measureUnit: 'г' },
            { title: 'сахар', count: '50', measureUnit: 'г' },
        ],
        steps: [
            {
                stepNumber: 1,
                description: 'Смешать кефир, муку и сахар.',
                image: '/img/cook-steps/1.jpg',
            },
            { stepNumber: 2, description: 'Сформировать тесто.', image: '/img/cook-steps/2.jpg' },
            { stepNumber: 3, description: 'Жарить на сковороде.', image: '/img/cook-steps/3.jpg' },
        ],
    },
];

export const JUICIEST_LIST = [
    {
        id: '1',
        title: 'Кнели со спагетти',
        description:
            'Классическое сочетание нежных кнелей со спагетти. Идеально для семейного ужина.',
        image: '/img/juiciest-collection/1.jpg',
        category: ['second-dish'],
        subcategory: ['poultry-dish'],
        bookmarks: 85,
        likes: 152,
        date: '2024-03-01T00:00:00Z',
        portions: 4,
        nutritionValue: { calories: 300, proteins: 15, fats: 10, carbohydrates: 40 },
        ingredients: [
            { title: 'кнели', count: '300', measureUnit: 'г' },
            { title: 'спагетти', count: '200', measureUnit: 'г' },
            { title: 'соус', count: '100', measureUnit: 'мл' },
        ],
        steps: [
            { stepNumber: 1, description: 'Сварить спагетти.', image: '/img/cook-steps/1.jpg' },
            { stepNumber: 2, description: 'Подготовить кнели.', image: '/img/cook-steps/2.jpg' },
            { stepNumber: 3, description: 'Смешать и подавать.', image: '/img/cook-steps/3.jpg' },
        ],
    },
    {
        id: '2',
        title: 'Пряная ветчина по итальянски',
        description: 'Итальянская ветчина с пряным вкусом, идеально дополняет гарниры.',
        image: '/img/juiciest-collection/2.jpg',
        category: ['second-dish', 'national'],
        subcategory: ['meat', 'italian'],
        bookmarks: 159,
        likes: 257,
        recommendation: {
            avatar: '/img/avatars/1.jpg',
            name: 'Елена Высоцкая',
        },
        date: '2024-03-12T00:00:00Z',
        portions: 4,
        nutritionValue: { calories: 350, proteins: 18, fats: 22, carbohydrates: 15 },
        ingredients: [
            { title: 'ветчина', count: '300', measureUnit: 'г' },
            { title: 'специи', count: '10', measureUnit: 'г' },
        ],
        steps: [
            { stepNumber: 1, description: 'Нарезать ветчину.', image: 'url' },
            { stepNumber: 2, description: 'Приправить специями.', image: '/img/cook-steps/2.jpg' },
            { stepNumber: 3, description: 'Запечь в духовке.', image: '/img/cook-steps/3.jpg' },
        ],
    },
    {
        id: '3',
        title: 'Лапша с курицей и шафраном',
        description: 'Ароматная лапша с курицей и шафраном — идеальное сочетание для обеда.',
        image: '/img/juiciest-collection/3.jpg',
        category: ['second-dish', 'national'],
        subcategory: ['poultry-dish'],
        bookmarks: 258,
        likes: 342,
        recommendation: {
            avatar: '/img/avatars/2.jpg',
            name: 'Alex Cook',
        },
        date: '2024-03-08T00:00:00Z',
        portions: 4,
        nutritionValue: { calories: 400, proteins: 30, fats: 15, carbohydrates: 50 },
        ingredients: [
            { title: 'лапша', count: '200', measureUnit: 'г' },
            { title: 'курица', count: '300', measureUnit: 'г' },
            { title: 'шафран', count: '1', measureUnit: 'ч. л.' },
            { title: 'лук', count: '1', measureUnit: 'шт.' },
        ],
        steps: [
            { stepNumber: 1, description: 'Сварить лапшу.', image: 'url' },
            {
                stepNumber: 2,
                description: 'Обжарить курицу с луком и шафраном.',
                image: '/img/cook-steps/2.jpg',
            },
            {
                stepNumber: 3,
                description: 'Смешать лапшу с курицей.',
                image: '/img/cook-steps/3.jpg',
            },
        ],
    },
    {
        id: '4',
        title: 'Том-ям с капустой кимчи',
        description: 'Острое блюдо с насыщенным вкусом капусты кимчи.',
        image: '/img/juiciest-collection/4.jpg',
        category: ['first-dish', 'national'],
        subcategory: ['soups', 'spicy-food'],
        bookmarks: 124,
        likes: 324,
        date: '2024-03-10T00:00:00Z',
        portions: 2,
        nutritionValue: { calories: 250, proteins: 8, fats: 10, carbohydrates: 22 },
        ingredients: [
            { title: 'грибы', count: '150', measureUnit: 'г' },
            { title: 'кимчи', count: '100', measureUnit: 'г' },
            { title: 'креветки', count: '200', measureUnit: 'г' },
            { title: 'специи', count: '0', measureUnit: 'по вкусу' },
        ],
        steps: [
            { stepNumber: 1, description: 'Подготовить кимчи.', image: 'url' },
            {
                stepNumber: 2,
                description: 'Добавить грибы и специи.',
                image: '/img/cook-steps/2.jpg',
            },
            { stepNumber: 3, description: 'Тушить до готовности.', image: '/img/cook-steps/3.jpg' },
        ],
    },
];

export const CULINARY_BLOGS = [
    {
        id: 1,
        userName: 'Елена Высоцкая',
        nickName: '@elenapovar',
        text: 'Как раз после праздников, когда мясные продукты еще остались, но никто их уже не хочет, время варить солянку.',
        avatar: '/img/avatars/1.jpg',
    },
    {
        id: 2,
        userName: 'Alex Cook',
        nickName: '@funtasticooking',
        text: 'Как раз после праздников, когда мясные продукты еще остались, но никто их уже не хочет, время варить солянку.',
        avatar: '/img/avatars/2.jpg',
    },
    {
        id: 3,
        userName: 'Екатерина Константинопольская',
        nickName: '@bake_and_pie',
        text: 'Как раз после праздников, когда мясные продукты еще остались, но никто их уже не хочет, время варить солянку.',
        avatar: '/img/avatars/3.jpg',
    },
];
