export const RECIPE_BUTTON_STYLES = {
    display: 'flex',
    gap: 3,
    boxSize: '208px',
    alignItems: 'center',
    justifyContent: 'center',
    color: 'blackAlpha.700',
    pl: { xl: 8 },
    _hover: { borderColor: 'transparent' },
    _focus: { outline: 'none' },
    sx: {
        textDecoration: 'none',
        color: 'black',
        '& .icon-container': {
            position: 'relative',
            '&::before': {
                content: '""',
                position: 'absolute',
                top: '0',
                left: '0',
                right: '0',
                bottom: '0',
                borderRadius: '50%',
                boxShadow: '0 0 40px 10px rgba(196, 255, 97, 0.6)',
                zIndex: -1,
            },
            '&::after': {
                content: '""',
                position: 'absolute',
                top: '-20px',
                left: '-40px',
                right: '-40px',
                bottom: '-40px',
                borderRadius: '50%',
                background:
                    'radial-gradient(circle, rgba(196, 255, 97, 0.3) 0%, rgba(255, 255, 255, 0) 100%)',
                zIndex: -1,
            },
        },
    },
};
