export enum ApiEndpoints {
    POSTS = '/posts/',
    CATEGORIES = '/category',
    RECIPES = '/recipe',
    AUTH_SIGNUP = '/auth/signup',
    AUTH_LOGIN = '/auth/login',
    AUTH_REFRESH = '/auth/refresh',
    AUTH_CHECK_AUTH = '/auth/check-auth',
    AUTH_VERIFY = '/auth/verify',
    AUTH_FORGOT_PASSWORD = '/auth/forgot-password',
    AUTH_VERIFY_OTP = '/auth/verify-otp',
    AUTH_RESET_PASSWORD = '/auth/reset-password',
    UPLOAD_FILE = '/file/upload',
    MEASURE_UNITS = '/measure-units',
    RECIPE_DRAFT = '/recipe/draft',
    BLOGGERS = 'bloggers',
    USERS_SUBSCRIPTION = 'users/toggle-subscription',
}
